### ISSUE TITLE
issues with plugin

### ISSUE THREAD

**Issue by jmmorrisonL** [benov84/homebridge-chromecast-television#12]
I keep getting this error, chrome cast docent seem to want to work 

[7/3/2021, 10:02:21 PM] Loaded plugin: homebridge-chromecast-television@1.0.9
[7/3/2021, 10:02:21 PM] ====================
[7/3/2021, 10:02:21 PM] ERROR INITIALIZING PLUGIN homebridge-chromecast-television:
[7/3/2021, 10:02:21 PM] ReferenceError: homebridhe is not defined
    at Plugin.module.exports [as pluginInitializer] (/usr/local/lib/node_modules/homebridge-chromecast-television/index.js:1006:3)
    at Plugin.initialize (/usr/local/lib/node_modules/homebridge/src/plugin.ts:203:10)
    at PluginManager.initializePlugin (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:158:14)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:147:12
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:124:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:24)
[7/3/2021, 10:02:21 PM] ====================

**Comment by skyfacexD** [comment]
Same....

**Comment by benov84** [comment]
Fixed in version 1.0.10. Please update
