### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by leftytennis** [benov84/homebridge-chromecast-television#18]
Hi, I just installed this plugin for homebridge and receive the following error after restarting homebridge:

```
[10/4/2021, 11:01:15 AM] Error: dns service error: unknown
    at new Browser (/homebridge/node_modules/mdns/lib/browser.js:88:10)
    at Object.create [as createBrowser] (/homebridge/node_modules/mdns/lib/browser.js:116:10)
    at new ControlChromecastPlatform (/homebridge/node_modules/homebridge-chromecast-television/index.js:47:29)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
```
Can you help figure out what's wrong? Thanks

**Comment by benov84** [comment]
check this please #17
