### ISSUE TITLE
Cannot find module 'hap-nodejs' after latest update

### ISSUE THREAD

**Issue by WesleyLiekens** [benov84/homebridge-chromecast-television#5]
After the latest update I get this error

[5/31/2021, 4:36:05 PM] ====================
[5/31/2021, 4:36:05 PM] ERROR LOADING PLUGIN homebridge-chromecast-television:
[5/31/2021, 4:36:05 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-chromecast-television/custom-characteristics.js
- /usr/local/lib/node_modules/homebridge-chromecast-television/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chromecast-television/custom-characteristics.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)

**Comment by WesleyLiekens** [comment]
i Also get

[5/31/2021, 4:40:00 PM] No plugin was found for the platform "ChromecastTelevision" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by benov84** [comment]
Install the new version 1.0.8 please, it includes hap-nodejs
