### ISSUE TITLE
DNS Service Error on startup

### ISSUE THREAD

**Issue by chandrasekharmalladi** [benov84/homebridge-chromecast-television#6]
```
Initializing ChromecastTelevision platform...
[6/8/2021, 8:17:46 PM] Error: dns service error: unknown
    at new Browser (/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/lib/browser.js:88:10)
    at Object.create [as createBrowser] (/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/lib/browser.js:116:10)
    at new ControlChromecastPlatform (/homebridge/node_modules/homebridge-chromecast-television/index.js:47:29)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[6/8/2021, 8:17:46 PM] Got SIGTERM, shutting down Homebridge...
```

I run into this on restarting homebridge.

I am running homebridge on a docker image - oznu/homebridge:raspberry-pi

**Comment by hipstersmoothie** [comment]
I think this may actually be the root of all of your open issues for your homebrdige chromecast repose @benov84 

Adding some instructions for people running this in docker (especially for people like me who have little experience with it) would go a really long way.

**Comment by hipstersmoothie** [comment]
From what I can tell the correct libs are installed in the recommended docker image

https://github.com/oznu/docker-homebridge/blob/master/Dockerfile.ubuntu

**Comment by benov84** [comment]
cl
